table Param_BinSize
	lineageTag: 334a5d71-bce2-49f0-bfe1-a1c6cc35830c

	column 'Bin Size'
		dataType: string
		lineageTag: 3165145e-3774-4cd1-a8a3-89735b4ffaf9
		summarizeBy: none
		sourceColumn: Bin Size
		sortByColumn: Sorting

		extendedProperty ParameterMetadata =
				{
				  "version": 2,
				  "kind": 1,
				  "selectAllValue": "__SelectAll__"
				}

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Sorting
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 92c88f2b-f6bf-46c5-8054-4ca80939dc5c
		summarizeBy: sum
		sourceColumn: Sorting

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Explanation
		dataType: string
		lineageTag: af200870-90f8-47df-b06c-4b912fb4e0fe
		summarizeBy: none
		sourceColumn: Explanation

		annotation SummarizationSetBy = Automatic

	partition Param_BinSize = m
		mode: import
		queryGroup: 'Parameter Table'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMkxR0lEyBGEFl8RKpVidaCVTkJAREJuChIrBYsYGIEFjsDrf/LySDLCooQVY2ASIzSDCUNVmYDNMwcojUxOLoKqNwMJmYKNBwnDVYGPMQcoNYBKxAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Bin Size" = _t, Sorting = _t, Explanation = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Bin Size", type text}, {"Sorting", Int64.Type}, {"Explanation", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

